joakim-brannstrom/dextool

.gitignore, autobuild.sh, build.sh, clang/TranslationUnit.d, dub.sdl, test/func_tests.sh, test/run_cstub_tests.sh, test/run_profile_test.sh, test/testdata/stage_4/fused_gtest/gtest/gtest-all.cc, test/testdata/stage_4/fused_gtest/gtest/gtest.h
RefCounted is slow, therefore removed redundant usage.
=> Profiling support

dub.sdl
changes in the structure of the application main resulted in too many files being excluded from compilation.
=> fix compiler error for development tool

build.sh, dub.sdl, source/test/tok_main.d
needed to understand if it was possible to use semanticParent to gather
info about namespaces a referenced class reside in.
Answer: Yes it is.
=> updated dev tools to allow backtracking

source/cpptooling/generator/gmock.d, test/testdata/cpp/dev/class_interface_more_than_10_params.hpp, test/testdata/cpp/dev/class_interface_more_than_10_params_gmock.hpp.ref
Make it possible to mock methods with more than 10 parameters
Mock methods for interface methods with more than 10 parameters are split into 
several partial mock methods. User of mock object can set expectations on each
partial mock method. Return values should be set for the last partial mock method.
Fix for issue #21
=> Workaround for google mock methods with more than 10 parameters

source/cpptooling/generator/gmock.d, test/testdata/cpp/dev/class_const_gmock.hpp.ref, test/testdata/cpp/dev/class_interface_gmock.hpp.ref, test/testdata/cpp/dev/class_interface_more_than_10_params_gmock.hpp.ref, test/testdata/cpp/dev/class_multiple_gmock.hpp.ref, test/testdata/cpp/dev/class_variants_interface_gmock.hpp.ref, test/testdata/cpp/dev/functions_gmock.hpp.ref, test/testdata/cstub/stage_1/param_gmock_gmock.hpp.ref
The C++ standard states that if a class with one or more virtual functions
but missing the virtual destructor is deleted it is undefined behavior.
=> Bug: add generation of virtual destructor to gmocks

test/cpp_tests.d, test/cstub_tests.d, test/utils.d
-Wpedantic is especially problematic. It is called -pedantic in older
compilers.
=> test: detect compiler flags at runtime

test/cstub_tests.d
on some platforms.
It isn't important to try and compile so skip it.
The test is just to ensure that -nostdinc doesn't really remove them,
the builtin libs are used.
=> bug: differences in provided stdlibs result in failing

test/cpp_tests.d, test/cstub_tests.d, test/external_tests.sh, test/utils.d
By using the module constructor it is ensured that before anything is
ran the logging is configured.
=> test: raise condition when configuring scriptlike yap

plugin/backend/cppvariant.d, plugin/backend/cvariant.d
Better encapsulation and understanding of the code by not spreading out
the variables holding the generated data.
=> refactor: Separate the generated data to a struct

plugin/backend/cvariant.d, plugin/backend/plantuml.d, source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/type.d, source/cpptooling/data/representation.d, test/testdata/cpp/dev/functions.hpp
Main problem is how function prototypes is handled.
Solved by separating those from other kinds.
Add contracts to ensure that info.type is never null in the future.
=> bug: info.type isn't correctly set thus null string

plugin/backend/plantuml.d, source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/clang/utility.d, source/cpptooling/analyzer/type.d, source/cpptooling/data/representation.d, source/cpptooling/generator/adapter.d, test/ut_main.d
Ensure no leading whitespace of the type information by using contracts.
=> Reduce simple data coupling by using Flag instead of bool

plugin/backend/cppvariant.d, plugin/backend/plantuml.d, source/cpptooling/analyzer/clang/visitor.d, source/cpptooling/data/representation.d, source/cpptooling/generator/adapter.d, source/cpptooling/generator/classes.d, source/cpptooling/generator/func.d, source/cpptooling/generator/gmock.d, test/plantuml_tests.d, test/testdata/uml/dev/abstract_interface.hpp, test/testdata/uml/dev/abstract_interface.pu.ref
Separate the classification type used for methods and classes to allow
specialization of the type.
=> PlantUML plugin doesn't classify abstract classes

source/cpptooling/analyzer/clang/type.d, test/testdata/cstub/stage_1/arrays.h, test/testdata/cstub/stage_1/arrays_global.cpp.ref, test/testdata/cstub/stage_1/function_pointers.h, test/testdata/cstub/stage_1/function_pointers.hpp.ref, test/testdata/cstub/stage_1/function_pointers_global.cpp.ref, test/testdata/cstub/stage_1/functions.cpp.ref, test/testdata/cstub/stage_1/functions.h, test/testdata/cstub/stage_1/functions.hpp.ref, test/testdata/cstub/stage_1/param_gmock.hpp.ref, test/testdata/cstub/stage_1/param_gmock_gmock.hpp.ref
Results in declarations missing the suffix "[<optional>]".
The tests for passing arrays of primitive types do not trigger the bug.
They are added for completeness.
=> Typedef's of arrays are wrongly classified

source/cpptooling/analyzer/clang/type.d
They still depend on the order that the files are analyzed but otherwise
they are deterministic.
=> Make the USR's deterministic

plugin/frontend/cpptestdouble.d, plugin/frontend/ctestdouble.d, plugin/frontend/plantuml.d, source/application/compilation_db.d, source/cpptooling/analyzer/clang/type.d, test/cstub_tests.d
Allows the user to look in the DB for "file" and copy and paste
or autocomplete in the shell to the file.
=> Support searching for a relative or absolute path in CompilationDatabase

.gitignore, autobuild.d, dsrcgen/source/dsrcgen/c.d, dsrcgen/source/dsrcgen/plantuml.d, source/cpptooling/analyzer/clang/analyze_helper.d, source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/clang/utility.d, source/cpptooling/analyzer/kind.d, source/cpptooling/data/class_classification.d, source/cpptooling/data/type.d
Fix documentation of public declarations.
Improve generated documentations usability by using ddox instead of the builtin docgen (ddoc).
Consolidate code that do basically the same thing (DRY).
=> refactor: improve maintenance

.travis.yml, autobuild.d, dub.sdl
unrelated changes by moving it to inside a configuration.
In the same PR fixing interaction between Travis/CodeCov
=> Avoid the forced rebuild that preBuildCommands introduces for

source/cpptooling/analyzer/clang/type.d, test/testdata/cstub/stage_1/functions.cpp.ref, test/testdata/cstub/stage_1/functions.h, test/testdata/cstub/stage_1/functions.hpp.ref, test/testdata/cstub/stage_1/param_gmock.hpp.ref, test/testdata/cstub/stage_1/param_gmock_gmock.hpp.ref
function ptr is derived from the return value.
=> Bugfix: function signature for a function returning a typedef:ed

plugin/backend/cvariant.d, plugin/backend/plantuml.d, source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/kind.d, source/cpptooling/analyzer/type.d, source/cpptooling/data/representation.d, source/test/component/analyzer/type.d, test/testdata/cstub/stage_1/functions.h
via typedef:s.
Fixes a bug where the location, which is crucial it is correct when
filtering symbols, is from where the function is declared and not the
typedef signatures location.
=> Missing the concept of a function signature which is present in C/C++

source/cpptooling/data/symbol/container.d
symbol being found multiple times.
It is not an error, therefore changing to a trace.
It should be used as an optimization opportunity.
=> Current implementation of type deduction result in the definition of a

source/application/compilation_db.d, test/testdata/compile_db/db1.json, test/testdata/compile_db/db2.json, test/testdata/cpp/compile_db/single_file_db.json, test/testdata/cstub/compile_db/db.json, test/testdata/cstub/compile_db/single_file_db.json, test/testdata/uml/compile_db/bad_code_db.json, test/testdata/uml/compile_db/merge_nested_ns_db.json, test/testdata/uml/compile_db/multi_file_db.json, test/testdata/uml/compile_db/single_file_db.json, test/testdata/uml/compile_db/two_file_db.json
The computation must take into consideration the compilation database
files location.
=> Paths from a compilation DB are incorrectly computed

source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/clang/utility.d
Add function for backtracking without skipping nodes to allow user
defined filtering.
=> Generalise backtracking of the clang AST

test/cpp_tests.d, test/cstub_tests.d, test/plantuml_tests.d, test/utils.d
Changed the default for c/c++ to not sort.
Should work well because they are sorted by the function/methods.
Plantuml though need to be sorted because the unique ID is derived
from the absolute path.
=> test: hard to compare the diff when it is sorted

source/application/compilation_db.d, source/application/types.d
which makes the --in=... from the user fail in mysterious ways from
the users perspective.
=> The file path in a compilation database isn't normalized

config.sh
Missing character which made running dextool on mac not working!
=> Missing a character in config.sh

plugin/frontend/ctestdouble.d
The xml file format is more common than .ini.
Better tooling.
=> ctestdouble: change generated logfile to an xml file

plugin/backend/ctestdouble/adapter.d, plugin/backend/ctestdouble/cvariant.d, test/testdata/cstub/stage_1/param_no_zeroglobals.h, test/testdata/cstub/stage_1/param_no_zeroglobals_no.cpp.ref, test/testdata/cstub/stage_1/param_no_zeroglobals_no.hpp.ref, test/testdata/cstub/stage_1/param_no_zeroglobals_yes.cpp.ref, test/testdata/cstub/stage_1/param_no_zeroglobals_yes.hpp.ref
even though the user has specified --no-zeroglobals.
=> Fix bug where an instance of a ZeroGlobals is generated

source/cpptooling/analyzer/clang/type.d, source/cpptooling/data/representation.d, source/cpptooling/utility/global_unique.d
Numbers that must be unique are generated in thread local which mean
they may be repeated in sibling threads.
The uniqe numbers in representatin and ..clang/type.d must be globally
unique because they are both used for USR's
storage which mean that they may not be u
=> Fix global unique identifiers to ensure they are not duplicated

source/cpptooling/data/representation.d
based on the variable name.
Changed to USR which _should_ be more unique.
=> CxGlobaVariable may not be unique because the ID is

plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/backend/cppvariant.d, plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/frontend/cpptestdouble.d, test/cpp_tests.d
=> cpptestdouble: allow the user to control generation of test doubles

CMakeLists.txt, DEVELOPER.md
integration tests can be executed.
=> test: missing that dextool binaries must be built before

plugin/ctestdouble/test/integration.d, source/dextool/clang.d
when deriving it from the compilation database.
=> dextool: user expect the --in file to be used if possible

source/cpptooling/analyzer/clang/ast/tree.d, source/cpptooling/analyzer/clang/ast/visitor.d
=> cpptooling: remove redundant test code from older versions of

clang/Cursor.d, source/test/CMakeLists.txt, source/test/component/analyzer/test_clang.d, source/test/component/scratch.d, source/test/ut_main.d
=> clang: the check always failed because the comparson is between enums of

test/source/dextool_test/compiler.d, test/source/dextool_test/utils.d
match the use case.
Only files are interesting to add.
Change the name to not easily be mixed up with addFilesFromOutdir.
It is a common case to want to exclude certain files.
=> test: adjust recursive adding of files to better

plugin/fuzzer/CMakeLists.txt, test/dextool_integration_test.cmake
=> cmake: fix recursive creation of symlinks on slow filesystems

cmake/Modules/BuildD.cmake, travis.sh
it hard to navigate and find the relevant stuff.
=> cmake: coverage data pollutes the build directory making

dextool_clang.cmake, dextool_cpptooling.cmake, dextool_dextool.cmake
=> cmake: make the dependencies explicit on the libs that required

clang/Cursor.d
by the specialization IncludeCursor.
=> clang: remove function from the generic cursor that is covered

test/source/dextool_test/compiler.d, test/source/dextool_test/utils.d
which lead to random failures.
By creating the logfile when finishing the test it should be more
stable.
=> test: creating the logfile on NFS filesystems are unreliable

plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/backend/generate_cpp.d, plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/frontend/frontend.d, plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/frontend/raw_args.d, plugin/cpptestdouble/test/gtest_integration.d, plugin/cpptestdouble/testdata/stage_3/test_order_req_for_recursive_structs.cpp, plugin/cpptestdouble/testdata/stage_3/test_pretty_print_in_ns.cpp, plugin/cpptestdouble/testdata/stage_3/test_pretty_print_in_ns.hpp
=> cpptestdouble: fix not generating pretty printers for structs

plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/backend/visitor.d
It is already performed by analyzeRecord.
=> cpptestdouble: remove redundant type analysis

plugin/mutate/source/dextool/plugin/mutate/backend/report.d
Add an additional newline after the header.
=> mutate: (report) header not identified by markdown parsers

plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d
makes it hard for the user to understand why the tool does nothing.
=> mutate: no user msg when the tool mode isn't specified which

plugin/mutate/source/dextool/plugin/mutate/backend/report.d
because it is an observable change of the behaviour.
=> mutate: timeout mutants should count as killed

plugin/compiledb/source/dextool/plugin/compiledb/raw_args.d, source/application/app_main.d
plugin because it knows what it is via arg[0]. Therefore stripping the
second argument.
=> application: the name of the plugin isn't necessary when calling a

plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
current directory always being part of the restricted directories.
=> mutate: multiple --restrict append to the default which result in the

plugin/mutate/source/dextool/plugin/mutate/backend/admin.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d
are change to.
This solve the problem where one may want to "force" mutants into the
timeout status because there are "too many" of them that takes too long
time to retest.
=> mutate: the CLI command admin should be able to control what the mutants

plugin/mutate/doc/design/mutations.md
github rendering of markdown pages.
=> mutate: (doc) remove ticks from the text because it wreaks havoc with

clang/Cursor.d, clang/Index.d, clang/TranslationUnit.d, clang/Util.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyzer.d, source/cpptooling/analyzer/clang/context.d, source/dextool/clang.d, source/dextool/utility.d
=> clang: fix memory leak because Index and TranslationUnit aren't

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/gtest_post_analyze.d
=> mutate: make gtest parser resiliant against accidental junk such as a

plugin/mutate/source/dextool/plugin/mutate/backend/report/markdown.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/plain.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/utility.d
test cases.
This hopefully improve the understanding for the user of why they
overlap.
=> mutate: improve visualisation of redundant test cases

plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
when generating with admin --init results in confusing errors.
=> mutate: not all users have a compile commands thus the active section

plugin/mutate/source/dextool/plugin/mutate/backend/database/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/nodes.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_stats.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/utility.d
By presenting kind:line it is easier for a user to get a quick overview
of the potential problems in the test group and the specific files.
=> mutate: (html) users cannot take fast actions on the mutation IDs

plugin/mutate/source/dextool/plugin/mutate/backend/diff_parser.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_user.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/utility.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/test/test_report.d, plugin/mutate/testdata/report_one_ror_mutation_point.cpp.diff
into relative for lookup in the database.
=> mutate: paths from a diff should be absolute so they then can be turned

plugin/mutate/source/dextool/plugin/mutate/backend/generate_mutant.d
This change makes mutated C code compatible with C89.
=> mutate: define fail_on_zero_dextool and abs_dextool as macros instead of templates

plugin/mutate/examples/triangle/1_setup.sh, plugin/mutate/examples/triangle/2_analyze.sh, plugin/mutate/examples/triangle/3_test.sh, plugin/mutate/examples/triangle/4_report.sh, plugin/mutate/examples/triangle/Makefile, plugin/mutate/examples/triangle/build.sh
Makefile now also tracks dependencies to source code and restarts mutation
analysis accordingly.
=> simplify the triangle mutate example, e.g. by reducing the number of files

source/dextool/clang.d, source/dextool/compilation_db/package.d, source/dextool/compilation_db/user_filerange.d
clang when parsing source code.
=> dextool: improve trace logging of what compiler flags are passed on to

plugin/mutate/doc/design/mutations.md, plugin/mutate/source/dextool/plugin/mutate/backend/visitor.d, plugin/mutate/test/mutate_dcc.d, plugin/mutate/test/mutate_stmt_deletion.d, plugin/mutate/testdata/dcr_bool_func.cpp
behavior by
* sdl. stop deleting call expressions inside return statements.
* dcr. return true/false for bool functions.
=> mutate: (dcr/sdl) reduce generated mutants that trigger undefined

plugin/mutate/source/dextool/plugin/mutate/backend/report/html/tmpl.d
Test cases can not affect mutation points that are killed by the compiler. The idea of the selected color ([#eeeeee](https://www.color-hex.com/popular-colors.php)) is to indicate that the mutation result for such mutants can be disregarded in the context of test effectiveness.
=> mutate: (html) change color for killed by compiler

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/visitor.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/aor.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/lcr.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/lcrb.d, plugin/mutate/test/generate_mutant.d, plugin/mutate/test/test_mutant_tester.d, plugin/mutate/test/test_report.d
The latest changes ended up mutating expressions that isn't strictly
connected to the intended operators.
=> mutate: fixup for lcr/lcrb/aor

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d, plugin/mutate/test/test_config.d, plugin/mutate/testdata/config/specify_sys_compiler/.dextool_mutate.toml, plugin/mutate/testdata/config/specify_sys_compiler/compile_commands.json, plugin/mutate/testdata/config/specify_sys_compiler/fake_cc.d, source/dextool/clang.d, source/dextool/compilation_db/package.d, source/dextool/compilation_db/system_compiler.d, source/dextool/compilation_db/user_filerange.d, test/source/dextool_test/utils.d
compile_commands.json.
This is useful for the analyze phase when the C++ standard library isn't
compatible with the clang frontend. Such is the case for e.g. gcc-4.X
=> mutate: allow the user to override the compiler from the

cmake/Modules/FindDCompiler.cmake
version installed in ubuntu xenial.
=> cmake: fix compare which fail in older versions of cmake such as the

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/visitor.d
This is hard to replicate but I think the problem is that the paths
aren't normalized.
=> mutate: mutation status results are wiped when copying DB from jenkins

plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/type.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d, plugin/mutate/test/test_report.d
The reason is that a mutant that span multiple lines may have the NOMUT
comment on a line different from the where it starts. Thus the
optimization that where used which only store the NOMUT per line failed.
The solution is to query the database for each mutant and get the
metadata for it. The con is that this is a bit slower but it works.
=> mutate: nomut is not always show in the html report

plugin/mutate/README.md, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/test/fixtures.d
and failed tests. This makes it possible for dextool to detect all test
cases that exist in the test suite.
=> mutate: make manual analyser command able to inform dextool of passed

plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d
removed is not re-tested correctly.
=> mutate: fix bug where the mutations killed by test cases that are

plugin/cpptestdouble/testdata/stage_3/pretty_print.hpp
which mean the tests fail sporadically.
=> cpptestdouble: member variables may contain random values in test case

plugin/mutate/view/source.js
=> mutate: the user can't see the inner scroll bar because it is overlaped

cmake/introspect_llvm.d
Removed the flags for osSpecificLinkerFlags so that Dextool can be built on macOS.
=> Fixed macOS linkerflags

plugin/mutate/doc/design/figures/test_mutant_fsm.pu, plugin/mutate/doc/design/figures/timeout_mutant.pu, plugin/mutate/doc/design/test_mutant/basis.md, plugin/mutate/doc/metadata.yaml, plugin/mutate/doc/pandoc.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/type.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/utility.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/timeout.d, plugin/mutate/source/dextool/plugin/mutate/backend/type.d, plugin/mutate/test/test_report.d, vendor/miniorm/source/miniorm/api.d
- multiple instances of dextool running in parallel
- only re-test those timeouts that has been changed
=> mutate: improve handling of timeout mutants

libs/dextool/source/dextool/utility.d, plugin/mutate/doc/design/analyzer/analyzer.md, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d, plugin/mutate/test/test_analyzer.d, plugin/mutate/testdata/analyze/exclude/file2.cpp, plugin/mutate/testdata/analyze/file1.cpp
This speeds up the analysis because the user can exclude those files
that aren't of interest to mutant such as external libraries.
=> mutate: allow the user to exclude files from being analyzed for mutants

plugin/mutate/source/dextool/plugin/mutate/backend/generate_mutant.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d
Remove unused functionality.
Tag required CLI parameter.
Wrap config specific data in its own type.
=> mutate: simplify and improve generate implementation

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d
mode. There are modes that do not require a database but because it
where always created by the frontend errored out.
=> mutate: only create a fused compile commands database when needed by a

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
=> mutate: allow the user to specify the test case analyzer as a shell

plugin/mutate/README.md, plugin/mutate/examples/algo_test/.dextool_mutate.toml, plugin/mutate/examples/game_tutorial/.dextool_mutate.toml, plugin/mutate/examples/gtest/.dextool_mutate.toml, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/test_cmd_runner.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/type.d
Allow the user to specify multiple test commands that are executed in
parallel.
Allow a user to specify the commands as an array of arguments. This
make it possible for the user to specify arguments that e.g. contains a
whitespace.
=> mutate: improve how a user can specify test, build and analyze commands

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/test_cmd_runner.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
=> mutate: allow the user to configure how many tests are executed in

plugin/mutate/source/dextool/plugin/mutate/backend/database/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/compiler.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/csv.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/markdown.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/plain.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/type.d
The improvement for a small example is from 12s to 0,3s.
The call to db.getTestCases(mutationId) was the culprit. It should only be done when it is needed.
=> mutate: fix performance regression when reporting statistics

plugin/mutate/source/process/channel.d, plugin/mutate/source/process/package.d
POLLHUP must also be checked because if it is set in revent it means
that there are data to read.
=> mutate: fix lockup in process draining of stdout/stderr

vendor/miniorm/source/miniorm/api.d
=> miniorm: add a limit to the number of cached statements to avoid an

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/common.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/test_cmd_runner.d, plugin/mutate/source/process/package.d
open thus the draining is waiting for data but it will never arrive.
=> mutate: fix livelock when a process is a zombie but keep stdout/stderr

plugin/mutate/source/process/package.d
=> mutate: always kill the process because it may be a sandbox which is

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/test_cmd_runner.d
Reduces the number of mutants marked as timeout when the available CPU
resources are variable for each mutant tested.
=> mutate: measure the worst case execution time of the test suite

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/gtest_post_analyze.d
the parameters in a parameterized test case merged.
=> mutate: adjust gtest test case name merge to be less greedy to make only

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
=> mutate: prettify the log message when measuring the runtime of the test

plugin/mutate/doc/design/mutations.md, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/package.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/type.d, plugin/mutate/test/test_mutant_tester.d, plugin/mutate/test/test_report.d
This set the operators, when the user doesn't specify one, to those that we have found most useful.
=> mutate: change default operators

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/common.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/gtest_post_analyze.d
The previous implementation didn't work but wasn't detected because the
test case where a bit too simplistic.
=> mutate: fix gtest segfault detection

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_schemata.d
=> mutate: more than one mutant can be added each loop thus missing the

plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d
=> mutate: fix db query that fail if the same schema is marked multiple

plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/aor.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/lcr.d, plugin/mutate/test/mutate_aor.d, plugin/mutate/test/mutate_lcr.d
removing lhs or rhs of these operators may change the expressions type
which lead to compilation errors when injected in the expression with
the ternery operator.
=> mutate: change lcr and aor to improve compatibility with schemata

plugin/mutate/source/dextool/plugin/mutate/backend/report/analyzers.d, plugin/mutate/test/test_report.d, vendor/miniorm/source/miniorm/api.d
It wrongly calculated the score based on the affected files when it
should have been the uniquely killed mutants.
=> mutate: fix diff score

plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d
the test phase.
This is because the schema tables allow the same mutation status ID to
be added multiple times with a relation to the schema. The InjectBuilder
in turn then removes mutants if they occur multiple times. The result is
that all mutants are removed just before the schema is executed.
=> mutate: workaround that a schema that contains mutants isn't executed in

plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d
=> mutate: ensure a schema do not have duplicate mutation status IDs

plugin/mutate/source/dextool/plugin/mutate/backend/admin.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/timeout.d
the once in the worklist has to be changed back to timeout.
=> mutate: to force testing of timeout mutants to stop as soon as possible

plugin/mutate/views/source.css
1) This fixes the problem that light pink (alive) vs mistyrose (unknown) can be easy to mix by mistake, by introducing a light yellow color for unknown.
2) It changes time-out mutants to use the same color brightness as killed mutants (light green), to reduce confusion.
=> mutate: fix html colors

plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
Output when using this patch:
```
[workarea]
[analyze]
[database]
[compiler]
[compile_commands]
[mutant_test]
test_cmd_dir = ["./build/test"]
build_cmd = ["./build.sh"]
use_early_stop = true
use_schemata = true
check_schemata = true
[report]
[test_group]
```
=> mutate: refactor init file description and format

plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
Output when using this patch:
```
[workarea]
[analyze]
[database]
[compiler]
[compile_commands]
[mutant_test]
build_cmd = ["./build.sh"]
test_cmd_dir = ["./build/test"]
use_early_stop = true
use_schemata = true
check_schemata = true
[report]
[test_group]
```
=> mutate: refactor init file description

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_mutant.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_schemata.d
and make it cheaper to share internally.
=> mutate: refcount the AST to allow it to be released by to the GC earlier

libs/cpptooling/source/cpptooling/analyzer/clang/check_parse_result.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
the default should not be commented out because the normal case is to use a compile_commands.json
=> mutate: fix default config and value for compile_commands.json

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
become unsure if the tool works as it should when Failed is printed.
=> mutate: improve the text when a schemata is not used because users

plugin/mutate/source/dextool/plugin/mutate/backend/report/compiler.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/csv.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_long_term_view.d
=> mutate: fix HTML and CVS report by printing mutation IDs as only their

plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/type.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
the runtime by saving the previous runs.
=> mutate: reduce the number of times the test suite is executed to measure

plugin/mutate/source/dextool/plugin/mutate/backend/report/analyzers.d, plugin/mutate/ut_main.d
this is to help a team earlier catch a change in the mutation score.
Without this it is discovered at the earliest the day after.
=> mutate: calculate the mean for each day

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/common.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/type.d
A string where split by whitespace into an array and they executed as a
command. This obviously failed.
=> mutate: fix build_cmd parse error

plugin/mutate/data/coverage_mmap.c, plugin/mutate/data/coverage_mmap.h, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/resource.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/coverage.d, plugin/mutate/test/test_covmap.cpp
This make it possible to mark a file as a root. It is those that are
analyzed which mean they come from e.g. a compile_commands.json.
=> mutate: only instrument root with coverage runtime

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/coverage.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
=> mutate: detect and halt mutation testing upon fatal error when running

plugin/mutate/doc/design/mutations.md, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_mutant.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/dcr.d, plugin/mutate/source/dextool/plugin/mutate/backend/type.d, plugin/mutate/test/test_mutant_tester.d
it is equivalent with SDL of case branches thus this is an unnecessary
overlap. Lets keep DCR focused on only boolean expressions.
=> mutate: remove DCR for case branches

plugin/mutate/data/source.css, plugin/mutate/data/source.js
fixes code comments causing a line-break at 60% of the window width
this was proabably made to make the "killing test case info box" be 60%,
but 100% width for that box should not be causing any problems.
=> mutate: change html code comments to 100% width

plugin/mutate/data/source.css, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
Example output:
(For example line 90 does not break)
=> fix html line-break and padding between code lines

plugin/mutate/doc/design/figures/test_mutant_fsm.pu, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
This way it is possible to see if the other mutants in the worklist
which test mutants that have a status changes the score.
=> mutate: save mutation score when all mutants are tested

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_mutant.d, plugin/mutate/test/test_report.d
Such as a void function with only comments.
=> mutate: do not generate sdl for blocks with no nodes

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_mutant.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/dcr.d, plugin/mutate/source/dextool/plugin/mutate/backend/type.d, plugin/mutate/test/mutate_dcr.d, plugin/mutate/test/test_analyzer.d, plugin/mutate/test/test_mutant_tester.d
It is redundant because the expr will be mutated.
=> mutate: remove returTrue/false for dcr

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_schemata.d, plugin/mutate/test/test_schemata.d, plugin/mutate/testdata/schemata_ternery.cpp
The new version off schematan should work because the original
expression is kept except for one condition being replaced.
=> mutate: enable schematas in ternery ops

libs/dextool_clang_extensions/cpp_source/macro.cpp, libs/dextool_clang_extensions/source/dextool/clang_extensions/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d
The clang queries are slow, about 3x slower than the previous
implementation.
=> mutate: use a cache for blacklist

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
=> mutate: new test cases should only be untagged when all alive/unknown

news.md, plugin/mutate/source/dextool/plugin/mutate/backend/report/analyzers.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/trend.d
Without this it goes between red/green without really saying anything.
The desired behavior is that when it is red it actually means that the
trend is "for sure" pointing downwards.
=> mutate: fix trend color to ignore small fluctuations

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/timeout.d
The purpuse is to ensure that the actually, used timeout is never <1s.
=> mutate: 1s limit should take effect after calc

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d
prohibit any progress if the number of timeout mutants are larger than
what can be processed during one --max-runtime.
=> mutate: timeout ctx is reset each time analyze is executed which

news.md, plugin/mutate/doc/design/figures/test_mutant_fsm.pu, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
Skip coverage because the user has specified exactly what to test thus
coverage is unnecessary.
=> mutate: improve speed for diff test

plugin/mutate/data/source.js, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
Now the backarrow works to actually go to previous-page. removed anchors when clicking on mutants etc
=> Backarrow fix

plugin/mutate/data/source.css, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/type.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/type.d
Visualizing coverage tests in mutation report by painting covered lines blue and non-covered lines red. 
Generating report is currently not working for a reason unknown to me.
The code for adding colors to the lines is currently commented out.
=> Coverage visualization

plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
Coverage lines now overlap with mutants
=> Show coverage on all lines

plugin/mutate/data/index.js
crash when tbody is undefined (when list is empty)
=> mutate: tbody crash

plugin/mutate/data/index.js
mutate site crashes when trying to add document time (not needed on this page)
=> mutate: doctime error fix

plugin/mutate/contributors.md
Obviously, one can check the "contributors" information under "Insights", but I feel like this is needed somewhere more public.
If I have forgotten someone, please tell me so that I can add them.
=> mutate: Add contributors.md

news.md, plugin/mutate/source/dextool/plugin/mutate/backend/admin.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/schemata.d, plugin/mutate/test/test_mutant_tester.d
The checksum used in MutationStatusTbl is changed to 64 bit and must be
unique. This is the requirement for a primary key thus by changing the
checksum to be the primary key the need for DB queries are reduced or
simplified.
=> mutate: simplify DB schema and queries

plugin/mutate/examples/game_tutorial/.dextool_mutate.toml
Using all operators for the example isn't necessary and makes it too slow to run when experimenting.
=> mutate: update game_tutorial config

plugin/mutate/README_roadmap.md, plugin/mutate/doc/design/figures/test_mutant_fsm.pu, plugin/mutate/source/dextool/plugin/mutate/backend/admin.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_schemata.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/type.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/common_actors.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/schemata.d, plugin/mutate/test/test_schemata.d
Instead of statically generating schemas of all available mutants move the generation to test to generate schemas based on what is in the worklist. It should result in schemas with a larger percentage of mutants that are tested.
=> mutate: move schemata to test phase

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/schemata.d
The purpose is to avoid running out of memory.
=> mutate: add upper limit of cached schema fragments

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d
Accidentally merged the prune schema ml model branch before CI passed.
=> mutate: fix broken master branch

libs/cpptooling/source/cpptooling/analyzer/clang/analyze_helper.d
=> ctestdouble: failed type deduction should not crash

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/timeout.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
The user need to be able to control the initial multiplier instead of the scale factor.
=> mutate: modify timeout calculation mainly for schema
