joakim-brannstrom/dextool

source/cpptooling/analyzer/clang/context.d, source/cpptooling/generator/stub/cstub.d, test/testdata/cstub/stage_1/class_func.hpp.ref, test/testdata/cstub/stage_1/function_pointers.hpp.ref, test/testdata/cstub/stage_1/functions.cpp.ref, test/testdata/cstub/stage_1/functions.hpp.ref, test/testdata/cstub/stage_1/param_gmock.hpp.ref, test/testdata/cstub/stage_1/param_main.cpp.ref, test/testdata/cstub/stage_1/param_main.h, test/testdata/cstub/stage_1/param_main.hpp.ref, test/testdata/cstub/stage_2/param_exclude_many_files.cpp.ref, test/testdata/cstub/stage_2/param_exclude_many_files.hpp.ref, test/testdata/cstub/stage_2/param_exclude_match_all.hpp.ref, test/testdata/cstub/stage_2/param_exclude_one_file.cpp.ref, test/testdata/cstub/stage_2/param_exclude_one_file.hpp.ref, test/testdata/cstub/stage_2/param_gen_pre_post_include.hpp.ref, test/testdata/cstub/stage_2/param_include.hpp.ref, test/testdata/cstub/stage_2/param_restrict.cpp.ref, test/testdata/cstub/stage_2/param_restrict.hpp.ref
Updated the generator and test cases to ad-her to Internet consensus regarding spelling
=> Adapter is the more common spelling

.gitignore, autobuild.sh, dub.sdl, source/cpptooling/data/representation.d, source/cpptooling/generator/cppvariant.d, source/cpptooling/generator/stub/cstub.d
=> bug: Compiling release when using unit_threaded

source/cpptooling/utility/taggedalgebraic.d
=> Updated tagged algebraic

source/cpptooling/generator/gmock.d, test/testdata/cpp/dev/class_interface_more_than_10_params_gmock.hpp.ref
=> Modified suffix for gmock methods with >10 params

autobuild.d
Changes the current behaviour that only dumps the log if an error occurred.
This is for example useful when studying the AST during development.
=> test: always dump the console log to allow seeing the test results

libclang/LICENSE.TXT
=> add Illinois/NCSA license

clang/Cursor.d, clang/SourceLocation.d, clang/SourceRange.d, clang/TranslationUnit.d, clang/Type.d, clang/Visitor.d, source/application/app_main.d, source/application/ctestdouble.d, source/cpptooling/analyzer/clang/context.d, source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/clang/utility.d, source/cpptooling/analyzer/type.d, source/cpptooling/data/representation.d, source/cpptooling/generator/adapter.d, source/cpptooling/generator/classes.d, source/cpptooling/generator/func.d, source/cpptooling/generator/stub/cstub.d, source/cpptooling/utility/clang.d, source/test/helpers.d, source/test/tok_main.d, test/cpp_tests.d, test/cstub_tests.d, test/testdata/cstub/inactive/enums.h, test/testdata/cstub/inactive/typedef_struct.h, test/utils.d
=> Fix style according to dfmt 0.5+

INSTALL.md, README.md, autobuild.d, build.sh, config.sh, dub.sdl, makefile, travis.sh
To allow users without dub to still build deXtool.
Solves #24
=> Build system using make

plugin/frontend/cpptestdouble.d, plugin/frontend/ctestdouble.d, source/application/utility.d
Prefer a language depending on frontend.
=> bug: When no language is specified C is preferred even though it is C++

.travis.yml, INSTALL.md, build.sh, makefile, travis.sh
Travis-CI for LDC is so far inactivated.
Waiting for release 1.0 of LDC.
=> Add support for compiling with LDC2

plugin/backend/plantuml.d, plugin/frontend/cpptestdouble.d, plugin/frontend/ctestdouble.d, plugin/frontend/plantuml.d, source/application/app_main.d, source/application/types.d, source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/type.d, source/cpptooling/data/representation.d, test/plantuml_tests.d, test/testdata/uml/dev/class_relate.hpp, test/testdata/uml/dev/class_relate.pu.ref
Using composition to visualize the relationship between classes.
Allow the user to control if class methods are generated.
Change and allow the user to control the generated filename.
=> Update plantuml plugin

plugin/backend/cppvariant.d, source/application/compilation_db.d, source/cpptooling/analyzer/clang/visitor.d, source/cpptooling/data/symbol/container.d, test/cpp_tests.d, test/testdata/cpp/dev/bug_class_not_in_ast.hpp
of classes when merging methods and constructing mocks.
=> Fix asserts that occurs when the AST is missing information

source/application/compilation_db.d
Too many incompatible with Clang.
=> When filtering compilation DB remove all flags starting with -f

dsrcgen/source/dsrcgen/plantuml.d, plugin/backend/plantuml.d, plugin/frontend/cpptestdouble.d, plugin/frontend/ctestdouble.d, plugin/frontend/plantuml.d, source/application/utility.d, source/cpptooling/data/representation.d, source/cpptooling/data/symbol/container.d, test/plantuml_tests.d, test/testdata/uml/cli/cli_comp_strip.hpp, test/testdata/uml/cli/cli_comp_strip.pu.ref, test/testdata/uml/cli/cli_comp_strip_complex.hpp, test/testdata/uml/cli/cli_comp_strip_complex.pu.ref, test/testdata/uml/cli/keep_this/b.hpp, test/testdata/uml/cli/strip_this/a.hpp, test/testdata/uml/component/a/a.hpp, test/testdata/uml/component/b/b_inherit_a.hpp, test/testdata/uml/component/b/b_member_to_a.hpp, test/testdata/uml/component/b/b_method_using_a.hpp, test/testdata/uml/component/class_inherit.hpp, test/testdata/uml/component/class_inherit.pu.ref, test/testdata/uml/component/class_member.hpp, test/testdata/uml/component/class_member.pu.ref, test/testdata/uml/component/class_method.hpp, test/testdata/uml/component/class_method.pu.ref, test/testdata/uml/dev/pure_interface.hpp, test/testdata/uml/dev/pure_interface.pu.ref
Built on the assumption that the directory structure reflects the components.
=> Data merge to generate UML diagrams

plugin/frontend/cpptestdouble.d, plugin/frontend/ctestdouble.d, plugin/frontend/plantuml.d, source/application/compilation_db.d, source/application/utility.d, test/cstub_tests.d, test/external_tests.sh, test/testdata/cstub/compile_db/file_not_found_msg.txt, test/utils.d
The message for the user is incomrehensible
=> Fix Compilation database error when file not found

plugin/frontend/plantuml.d
Therefor changed to no language.
=> Enforcing language C++ makes the plantuml plugin unsuitable for C

clang/Cursor.d, clang/File.d, clang/SourceLocation.d, plugin/backend/cppvariant.d, plugin/backend/cvariant.d, plugin/backend/plantuml.d, plugin/frontend/cpptestdouble.d, plugin/frontend/ctestdouble.d, plugin/frontend/plantuml.d, source/application/utility.d, source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/clang/visitor.d, source/cpptooling/analyzer/kind.d, source/cpptooling/analyzer/type.d, source/cpptooling/data/representation.d, source/cpptooling/data/symbol/container.d, source/cpptooling/data/type.d, source/cpptooling/generator/adapter.d, source/cpptooling/generator/gmock.d, source/cpptooling/generator/utility.d, test/plantuml_tests.d, test/testdata/uml/dev/bug_crash_on_sigset.pu.ref, test/utils.d
and thus indirectly fixing backtracking algorithm.
=> Fix representation of "no location"

plugin/backend/plantuml.d
Check that the TypeRef is to a record.
Check the element type of an array.
=> Fix plantuml classdiagram

plugin/backend/cppvariant.d, plugin/backend/cvariant.d, plugin/frontend/ctestdouble.d, source/cpptooling/data/representation.d, source/cpptooling/generator/classes.d, source/cpptooling/generator/func.d, source/cpptooling/generator/gmock.d, test/cstub_tests.d, test/testdata/cstub/stage_2/param_loc_as_comment.h, test/testdata/cstub/stage_2/param_loc_as_comment.hpp.ref, test/testdata/cstub/stage_2/param_loc_as_comment_global.cpp.ref, test/utils.d
=> Allow the user to control generation of origin information for each

plugin/frontend/ctestdouble.d, plugin/frontend/plantuml.d, source/cpptooling/analyzer/kind.d, test/testdata/uml/dev/bug_using.hpp, test/testdata/uml/dev/bug_using.pu.ref
Start counting files from one, not zero.
Fix typo.
Improve test case for using directive.
=> Fix count error and stuff

.gitignore, dub.sdl, gen_version_from_git.sh, makefile, source/application/app_main.d, test/ut_main.d
=> Automatically generate "--version" from the git archive during

README.md, plugin/backend/cvariant.d, plugin/backend/plantuml.d, plugin/frontend/ctestdouble.d, source/cpptooling/analyzer/clang/type.d, source/cpptooling/analyzer/kind.d, source/cpptooling/analyzer/type.d, source/cpptooling/generator/adapter.d
Remove redundant code and traces of old design regarding "stubs".
=> Remove redundant code and design traces

source/cpptooling/analyzer/clang/type.d, source/test/component/analyzer/type.d
Container because they had the same USR.
=> Fix bug where pointer types could accidentally be merged in the

source/cpptooling/data/representation.d, source/cpptooling/utility/taggedalgebraic.d
=> Use backported Unqual to ensure the project behaves correctly with

config.sh, dub.sdl, source/test/component/analyzer/type.d
Seems to fail one test "test.component.analyzer.type.Should be a type of kind 'func'", unable to test on linux at the moment to see if the same test fails there too.
=> mac support

source/cpptooling/analyzer/clang/utility.d, source/test/component/analyzer/utility.d, test/ut_main.d
=> Incorrectly classifying definitions as global when defined in

plugin/frontend/ctestdouble.d
files.
It is confusing for the reader what is information and what is
configuration.
=> ctestdouble: fix the mix of log and config data in the generated xml

test/.gitignore, test/external_main.d, test/utils.d
dedicated directory.
Easier to cleanup, follows good practice.
=> test: generate build artifacts and test data in a

INSTALL.md
A clean build seems to work better with make.
=> Fix INSTALL.md

source/application/plugin.d
besides those that are located beside the dextool binary.
=> Initial feature to discover additional plugins at runtime

dsrcgen/source/dsrcgen/c.d, dsrcgen/source/dsrcgen/cpp.d
=> dsrcgen: variadic arguments for expression templates in C++

autobuild.d
Running it on all files result in too many errors that aren't
actionable. Resulting in nothing being done.
=> Only run dscanner on those files that are changed

source/cpptooling/data/representation.d
and are slower than necessary when used in a AA.
This changes it to using a hash instead.
=> String based identifiers take up unnecessary memory

source/dextool/compilation_db.d
=> Add support in compilation database parsing for flags that take a path argument

dsrcgen/source/dsrcgen/c.d, dsrcgen/source/dsrcgen/sh.d, dsrcgen/test/ut.d, plugin/CMakeLists.txt, plugin/intercept/CMakeLists.txt, plugin/intercept/source/dextool/plugin/intercept/backend/analyzer.d, plugin/intercept/source/dextool/plugin/intercept/backend/backend.d, plugin/intercept/source/dextool/plugin/intercept/backend/interface_.d, plugin/intercept/source/dextool/plugin/intercept/frontend/intercept.d, plugin/intercept/source/dextool/plugin/intercept/frontend/raw_args.d, plugin/intercept/source/dextool/plugin/intercept/runner.d, plugin/intercept/source/dextool/plugin/intercept/type.d, plugin/intercept/test/integration.d, plugin/intercept/testdata/stage_1/function.cpp.ref, plugin/intercept/testdata/stage_1/function.h, plugin/intercept/testdata/stage_1/function.hpp.ref, plugin/intercept/testdata/stage_3/test_replace_single_sym/conf.xml, plugin/intercept/testdata/stage_3/test_replace_single_sym/main.cpp, plugin/intercept/testdata/stage_3/test_replace_single_sym/orig.c, plugin/intercept/testdata/stage_3/test_replace_single_sym/orig.h, plugin/intercept/testdata/stage_3/test_replace_single_sym/orig.hpp.ref, source/cpptooling/generator/utility.d
Generate an intercept layer around a library of free functions
=> plugin: add intercept

plugin/compiledb/test/integration.d, plugin/fuzzer/test/integration.d
but they should have been BSL-1 as every other test suite.
=> test: the license for the test suites are MPL-2

plugin/analyze/source/dextool/plugin/analyze/mccabe.d, plugin/analyze/test/integration.d
=> analyze: count and present the total McCabe value

clang/Compiler.d, clang/Cursor.d, clang/Diagnostic.d, clang/Index.d, clang/TranslationUnit.d, clang/Util.d, clang/Visitor.d, plugin/analyze/source/dextool/plugin/analyze/analyze.d, plugin/analyze/source/dextool/plugin/analyze/filerange.d, plugin/analyze/source/dextool/plugin/analyze/mccabe.d, plugin/analyze/source/dextool/plugin/analyze/raw_config.d, plugin/analyze/source/dextool/plugin/analyze/runner.d, plugin/analyze/source/dextool/plugin/analyze/visitor.d, source/cpptooling/analyzer/clang/check_parse_result.d, source/cpptooling/analyzer/clang/context.d, source/cpptooling/analyzer/clang/cursor_visitor.d, source/cpptooling/analyzer/clang/include_visitor.d, source/cpptooling/utility/virtualfilesystem.d, source/dextool/clang.d, source/dextool/utility.d, travis.sh
Annotates large parts of the clang glue layer with safe/trusted in the hope of finding potential memory corruption bugs.
=> analyze: minor GC optimization

plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/backend/backend.d, plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/backend/class_merge.d, plugin/cpptestdouble/test/config.d, plugin/cpptestdouble/test/integration_main.d, plugin/cpptestdouble/test/stage_1.d, plugin/cpptestdouble/test/utility.d, plugin/cpptestdouble/testdata/stage_1/bug_class_inherit.cpp, plugin/cpptestdouble/testdata/stage_1/bug_class_inherit.hpp, source/cpptooling/data/representation.d
=> cpptestdouble: fix deduplication bug

plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/backend/backend.d, plugin/cpptestdouble/source/dextool/plugin/cpptestdouble/backend/class_merge.d, plugin/cpptestdouble/test/gtest_integration.d, plugin/cpptestdouble/testdata/stage_1/test_pretty_print_generator.hpp
=> cpptestdouble: pretty printers generated for struct/classes with zero public members

source/dextool/type.d
filesystem.
This reduces the number of needed file checks.
=> dextool: add a type that guarantees that the file exists on the

cmake/Modules/FindLibClang.cmake, plugin/mutate/source/dextool/plugin/mutate/backend/mutate_operator.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutate_uoi.d, plugin/mutate/source/dextool/plugin/mutate/backend/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/visitor.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d, plugin/mutate/test/integration_main.d, plugin/mutate/test/mutate_uoi.d, plugin/mutate/testdata/unary_op_insert.cpp
Unary Operator Replacement don't exist as a specific mutation kind.
=> mutate: replace UOR with UOI

plugin/mutate/source/dextool/plugin/mutate/backend/linux_process.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant.d
=> mutate: env must be merged and passed on to the forked child

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d
the infrastructure has a spiky behaviour.
=> mutate: fixes to timeout, unused too modes and ensure SUT is built before tests are measured

plugin/mutate/source/dextool/plugin/mutate/backend/report.d
the user to look at in a markdown renderer.
=> mutate: use markdown syntax blocks for the data to make it pretty for

plugin/mutate/doc/design/future_work.md, plugin/mutate/source/dextool/plugin/mutate/backend/linux_process.d
Detect when the process become orphaned and suicide the pid session.
=> mutate: ctrl+c leave running processes behind

plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
=> mutate: update CLI description for analyzer to highlight what is the

plugin/mutate/source/dextool/plugin/mutate/backend/admin.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d, plugin/mutate/source/dextool/plugin/mutate/type.d
It is a bit too over-zealous for now because it removes the mutation
points. It should be improved in the future.
=> mutate: add admin interface for removing mutations

plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/package.d, plugin/mutate/test/test_report.d
=> mutate: adjust compiler report to convert the internal kind to the user

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/gtest_post_analyze.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
=> mutate: invalid UTF-8 chars forces the mutant to be retested in an

plugin/mutate/source/dextool/plugin/mutate/backend/generate_mutant.d, plugin/mutate/test/mutate_abs.d
mapped file whose content change via the preamble
=> mutate: fix erroneous mutants

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
because there are still open files.
=> mutate: fix error where directory wheren't removed on NFS systems

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
There can be stale file handlers in a tmp directory which mean that at
that specific time the directory can't be removed. But it will *most
probably* succeed at a later time when the NFS has synced up.
By keeping a list of temp directories and continuously trying to remove
them most cases of junk being left behind should be fixed.
=> mutate: fix cleanup of temp dirs on NFS systems

plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/markdown.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/plain.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/utility.d
=> mutate: overlap analysis and zero kills is controlled on what type of

plugin/mutate/README.md, plugin/mutate/examples/gtest/.dextool_mutate.toml
This reverts commit b9305c20d5912a6fb52b932abe706b8c38a32de8.
=> Partial Revert "mutate: add usage examples"

plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/utility.d
=> mutate: (html) reporting mutants of kinds that aren't specified by the

plugin/mutate/source/dextool/plugin/mutate/backend/analyzer.d
=> mutate: improve user experience by only printing the stack trace when

plugin/mutate/source/dextool/plugin/mutate/backend/generate_mutant.d
correctly for large blocks of code.
=> mutate: impl stmt del with comments do not nest

plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d
=> mutate: improve error messages when unable to open a

plugin/mutate/source/dextool/plugin/mutate/backend/database/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/js.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/tmpl.d
Update the html report to show the metadata for the mutant that is
marked.
=> mutate: the user wants to see if a mutant is ignored when NOMUT is used

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/test/test_report.d, plugin/mutate/testdata/report_nomut1.cpp, plugin/mutate/testdata/report_nomut1.hpp
=> mutate: fix suppressing of mutants that has a NOMUT at the end of its

plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/test/test_report.d
=> mutate: fix bug where the same mutant is reported multiple times in the

plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_test_case_similarity.d, plugin/mutate/test/test_report.d
difference more important to look at.
=> mutate: swap difference and intersection because the user consider the

plugin/mutate/examples/README.md, plugin/mutate/examples/algo_test/.dextool_mutate.toml, plugin/mutate/examples/algo_test/.gitignore, plugin/mutate/examples/algo_test/CMakeLists.txt, plugin/mutate/examples/algo_test/build.sh, plugin/mutate/examples/algo_test/run_demo_0.sh, plugin/mutate/examples/algo_test/run_demo_1.sh, plugin/mutate/examples/algo_test/run_demo_2.sh, plugin/mutate/examples/algo_test/run_demo_3.sh, plugin/mutate/examples/algo_test/src/impl.cpp, plugin/mutate/examples/algo_test/src/impl.hpp, plugin/mutate/examples/algo_test/test.sh, plugin/mutate/examples/algo_test/test/tests.cpp
in the test suite which lead to detecting and fixing the bug.
=> mutate: add example that highlight how mutation testing show the problem

DEVELOPER.md
I did not remove the vim file info. It looks a bit messy but I do not want people to hunt me down
=> Some grammar and spelling fixes to Developer.md

README.md
=> Some minor changes to spelling and grammar

README.md
=> readme: make the llvm dependencies more explicit

plugin/mutate/examples/game_tutorial/README.md
=> mutate: update readme of the example

libs/cpptooling/source/cpptooling/analyzer/clang/cursor_logger.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/visitor.d, plugin/mutate/test/mutate_dcc.d, plugin/mutate/test/mutate_stmt_deletion.d, plugin/mutate/testdata/sdl_return_del.cpp, test/source/dextool_test/sequence.d
=> mutate: delete return statement of void functions

libs/clang/source/clang/Token.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/utility.d, plugin/mutate/test/test_report.d, plugin/mutate/testdata/report_multi_line_comment.cpp
=> mutate: fix multiline comments in html report

plugin/mutate/doc/design/options.md
Added options.md in _plugin/mutate/doc/design_ that explains some of the flags available in _Mutate_.
Aims to solve [#928](https://github.com/joakim-brannstrom/dextool/issues/928) partly.
=> Mutate-update-documentation

plugin/mutate/doc/design/usability/report.md, plugin/mutate/source/dextool/plugin/mutate/backend/report/utility.d, plugin/mutate/test/test_report.d
=> mutate: change calculation of the mutation score by not counting

libs/dextool/source/dextool/type.d, libs/dextool/source/dextool/utility.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d
not current working directory.
=> mutate: fix bug where relative exclude paths should expand to root and

libs/dextool/source/dextool/compilation_db/package.d
The bug fix is the change from parts[0] to raw_flag when checking for a
match.
=> dextool: merge fixes from code_checker

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/test/test_mutant_tester.d
=> mutate: stop mutation testing after a specific number of alive mutants

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
files are analyzed for mutation changes.
=> mutate: allow a user to pipe a diff to the analyze phase to limit what

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d
Slight performance improvement and makes it possible to edit the tables.
=> mutate: convert views to tables

libs/dextool/source/dextool/set.d, plugin/mutate/source/dextool/plugin/mutate/backend/admin.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/type.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/analyzers.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/test/test_admin.d, plugin/mutate/test/test_analyzer.d, plugin/mutate/test/utility.d
=> mutate: improve analyze speed

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/common.d, plugin/mutate/test/test_mutant_tester.d, plugin/mutate/ut_main.d
=> mutate: fix infinite loop when the last output from the test suite is

plugin/mutate/test/test_config.d
=> mutate: fix test case that modified the original while other test cases

plugin/mutate/doc/design/test_mutant/tracker.md, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/gtest_post_analyze.d
=> mutate: reduce the clutter in the test case analysis by mergin

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d
database can't store the result fast enough.
=> mutate: improve memory usage by slowing down the analyzer if the

plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d
It fails on some versions, unknown why. Move it to a bound variabler
which is known to work.
=> mutate: fix db query

plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/schemata.d
schemata upgrade and possible null id.
=> mutate: fix bugs

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_mutant.d
rhs and op location where reveresed.
=> mutate: fix source location bug for binary op

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
Request from users because setting it later means it has a higher
discrepancy against expected runtime.
=> mutate: set max runtime as soon as possible

libs/dextool_clang_extensions/cpp_source/casestmt.cpp, libs/dextool_clang_extensions/source/dextool/clang_extensions/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_mutant.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_schemata.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/sdl.d, plugin/mutate/test/mutate_stmt_deletion.d, plugin/mutate/testdata/schemata_sdl.cpp
=> mutate: stop generarting sdl mutants that delete the whole content of a

plugin/mutate/source/dextool/plugin/mutate/backend/report/markdown.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/plain.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/test/test_report.d
This isn't all entry points but the most common.
=> mutate: print what mutation operators are used

plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
=> mutate: fix root and restrict defaults to mutate everything in the

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d
=> mutate: blacklist a mutant from schematan if it contains a blacklisted

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
Otherwise the schema may be useful in the future when e.g. a test case
is added and all alive is tested again.
=> mutate: only remove schemas that have killed all mutants

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_mutant.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/package.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d, plugin/mutate/source/dextool/plugin/mutate/frontend/frontend.d, plugin/mutate/test/test_analyzer.d, plugin/mutate/test/utility.d
=> mutate: reduce database size by allowing a user to specify what mutants

plugin/mutate/doc/design/figures/test_mutant_fsm.pu, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/source/dextool/plugin/mutate/frontend/argparser.d
=> mutate: add CI support for defining a behavior when the server is

plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/analyzers.d
Enforce uniqueness. There where a bug where multiple mutants status IDs
could be related to the same test case which among other things bloated
the database.
=> mutate: improve database schema for test cases

plugin/mutate/doc/design/future_work.md, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d, plugin/mutate/test/test_mutant_tester.d
=> mutate: change re-test to account for changes to the programs source

doc/install/UBUNTU.md
dmd lead to segfault when built for release
=> readme: update install instructions

plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d
=> mutate: fix upgrade to v33 of db schema to not remove all previous

plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
resolution. Changed to only minutes after conversation with users about
what they may care about.
=> mutate: (html) test time as it is printed is too large and high

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/ast.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_schemata.d, plugin/mutate/test/mutate_stmt_deletion.d, plugin/mutate/test/test_schemata.d, plugin/mutate/testdata/schemata_switch.cpp
This generates invalid schemas for googletest but I am unable to
reproduce.
=> mutate: fix call deletion

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/ast.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/dcr.d, plugin/mutate/test/mutate_dcr.d, plugin/mutate/test/test_schemata.d, plugin/mutate/testdata/dcr_cc_ifstmt2.cpp, plugin/mutate/testdata/schemata_binop.cpp
=> mutate: fix dcr mutants where the replaced type is different from the

plugin/mutate/data/coverage_mmap.c, plugin/mutate/data/schemata_header.c, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d
=> mutate: fixes

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d
=> mutate: clang builtin macro detection did not handle overlapping or

libs/libclang_ast/source/libclang_ast/ast/tree.d, news.md, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/extensions.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_clang.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d
Deleting files, which happens on a full re-analyze, is prohibitively
slow on a large project.
=> mutate: optimize sqlite

plugin/mutate/data/default.css, plugin/mutate/data/index.js, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_test_case.d, plugin/mutate/source/dextool/plugin/mutate/config.d, plugin/mutate/test/test_report.d
The table becomes hard to read and to find the problems
(buggy/redundant) when the number of test cases goes beyond 50.
=> mutate: improve readability of the test case table

plugin/mutate/data/index.js, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
=> mutate: (html) add file table filter

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/test_cmd_runner.d
Use available because that is actually the one requested. Free results
in too unstable memory check.
=> mutate: available and free pages are different

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/timeout.d
Ensures that they are re-tested at least once.
Makes sure that they are only tested a limited number of times.
=> mutate: change re-test of mem overload mutants

plugin/mutate/source/dextool/plugin/mutate/backend/analyze/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/analyze/pass_schemata.d
It has unbounded growth which results in crash.
=> mutate: limit schema fragment cache

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
Otherwise e.g. trend update do not work correctly because it only
samples when the worklist is zero. The testing could also end up in a
steady state wherein the --timeout is too short such that the worklist
never reach zero.
=> mutate: only add old mutants when worklist is empty

plugin/mutate/data/source.html, plugin/mutate/data/source.js
coverage toggle button fixed, was lost in manual merge earlier
=> Fix coverage toggle

plugin/mutate/data/source.js, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
clicking on mutant in file report with mouse now shows the smallest by text length mutant. List of mutants in info-box is also sorted by smallest text length
=> Priority hightlight

plugin/mutate/data/default.css, plugin/mutate/data/index.js, plugin/mutate/data/source.css, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_diff.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_mutant.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_stats.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_test_case.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_worklist.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/tmpl.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/trend.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/utility.d
- improved hover button slightly and added to more places
- made into help function instead
- added comment on section that needs to be changed/deleted to implement button
- improved design of "test cases", if clicked again the table is minimized
=> mutate: popup help

plugin/mutate/data/dashboard.html, plugin/mutate/data/index.js
If javascript isn't loaded a information text will show
=> mutate: csp error info added

plugin/mutate/data/source.css, plugin/mutate/data/source.js, plugin/mutate/source/dextool/plugin/mutate/backend/mutation_type/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
Shows a tooltip above the hovered mutant
=> mutate: Hover mutant

plugin/mutate/data/index.js
js crash when loading all mutants fix
=> mutate: csp crash mutate page fix

plugin/mutate/data/default.css
slightly improved the design of sortable table. Fixed so the arrow is clickable
=> mutate: sortable table design and arrow fix

plugin/mutate/data/index.js, plugin/mutate/data/source.js, plugin/mutate/data/table_on_click.js
ran vs code autoformat on js files
=> mutate: stylefix js files

plugin/mutate/data/default.css, plugin/mutate/data/index.js, plugin/mutate/data/source.css
Fixed so that the info box that appears on hover doesn't go off screen.
=> mutate: info text bar outside window on hover

plugin/mutate/CMakeLists.txt, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/page_test_case.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/utility.d
filter added for url and links involving testcase names. Generated text through js of testcase names have also been encoded to not create corrupted html files
=> mutate: testcase namefilter

plugin/mutate/source/dextool/plugin/mutate/backend/database/schema.d, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
Need to run autoformat, but the format changes a lot so it should maybe be run in a different PR?
=> mutate: Only one mutation-score per day

plugin/mutate/data/index.js, plugin/mutate/source/dextool/plugin/mutate/backend/database/standalone.d, plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
Can change the timeframe that the change column in the files table uses to calculate with
=> mutate: "Change" change timeframe

plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
=> mutate: (html) fix unable to view mutants

plugin/mutate/source/dextool/plugin/mutate/backend/report/html/trend.d
To calculate the average on the fly all file score data need to be
available.
=> mutate: (html) fix change column in index

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/schemata.d
Not all files contain fragments so keep on adding until at least one fragment has been added.
=> mutate: improve schema

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/schemata.d
It is only those mutants that are in the whitelist that will be tested thus this ensure that scheman are only built with fragments that contain such mutants.
=> mutate: only add schema fragments with whitelist mutants

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/schemata.d
Move it to a separate actor to simplify the logic in the schema test driver.
=> mutate: stabilize schema generator

Docker/docker.d, Docker/partial/build_test, Docker/partial/ubuntu_minimal_base, azure-pipelines.yml
=> ci: change ldc to only release

plugin/mutate/source/dextool/plugin/mutate/backend/test_mutant/package.d
=> Fixed typo

news.md, plugin/mutate/data/index.js
Date.parse started to return true in firefox which lead to the sort function not functioning correctly for numbers.
=> mutate: fix table sort

plugin/mutate/source/dextool/plugin/mutate/backend/report/html/package.d
Use correct sort predicate, the offset and not the pointer address.
=> mutate: fix html report
